import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MealStubProvider } from "@/context/MealStubContext";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meal Stub Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MealStubProvider>{children}</MealStubProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
